### ISSUE TITLE
[BUG][code-analyzer] .eslintrc.json override options ignored

### ISSUE THREAD

**Issue by DougMidgley** [forcedotcom/code-analyzer#1807]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

When running the v5 updates, I see that anything within the override key in eslint config seems to be ignored, despite eslint CLI reporting the issues. 
`npx eslint  common\app\lwc\example\example.js -f json -o codescan/code-eslint.json  produced` produced 17 errors
`sf code-analyzer run  --view detail -f codescan/code-scan.csv --workspace common\app\lwc\example\example.js  --config-file ./code-analyzer.yml` produced 0 errors, but did show "Parsing error: Unexpected token =" which suggests that the additional libs to parse LWC were failing to load, resulting in ESLINT OOTB not running. 

When moving the items in the override key into the main config, then everything works as expected

[.eslintrc.json](https://github.com/user-attachments/files/20234905/default.eslintrc.json)

code-analyzer.yml content

```
log_folder: /codescan
log_level: 5
engines:
    eslint:
        # Using ESLINT 8 until 9 is supported
        # disable_engine: true
        eslint_config_file: .eslintrc.json
        eslint_ignore_file: .eslintignore
        disable_javascript_base_config: true
        disable_lwc_base_config: true
        disable_typescript_base_config: true
        auto_discover_eslint_config: false
```

### Output / Logs

[sfca-2025_05_15_23_58_02_952.log](https://github.com/user-attachments/files/20234908/sfca-2025_05_15_23_58_02_952.log)

### Steps To Reproduce

1. Run `npx eslint  common\app\lwc\example\example.js -f json -o codescan/code-eslint.json  produced` produced 17 errors
2. `sf code-analyzer run  --view detail -f codescan/code-scan.csv --workspace common\app\lwc\example\example.js  --config-file ./code-analyzer.yml` produced 0 errors

### Expected Behavior

Number of errors reported should be identical. 
No errors on eslint rules should show in SF CLI where there is none shown in ESLINT CLI

### Operating System

Windows 11

### Salesforce CLI Version

@salesforce/cli@2.88.6 

### Code Analyzer Plugin (code-analyzer) Version

code-analyzer 5.0.0

### Node Version

v22.14.0

### Java Version

openjdk version "17.0.11" 2024-04-16 LTS OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS) OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)

### Workaround

Stay with v4 of scanner.

### Urgency

Moderate
